-- Architecture Version Control
-- Stores snapshots of architecture designs for history and rollback
-- Generated by SolsArch Phase 2 Implementation

CREATE TABLE public.architecture_versions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  architecture_id UUID REFERENCES public.architectures(id) ON DELETE CASCADE,
  version_number INTEGER NOT NULL DEFAULT 1,
  name TEXT NOT NULL,
  snapshot JSONB NOT NULL,
  change_summary TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Index for efficient queries
CREATE INDEX idx_architecture_versions_architecture_id ON public.architecture_versions(architecture_id);
CREATE INDEX idx_architecture_versions_created_at ON public.architecture_versions(created_at DESC);

-- Enable RLS
ALTER TABLE public.architecture_versions ENABLE ROW LEVEL SECURITY;

-- Version policies (access through architecture -> project ownership)
CREATE POLICY "Users can view versions of their architectures"
ON public.architecture_versions FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.architectures a
    JOIN public.projects p ON p.id = a.project_id
    WHERE a.id = architecture_versions.architecture_id
    AND p.user_id = auth.uid()
  )
);

CREATE POLICY "Users can create versions for their architectures"
ON public.architecture_versions FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.architectures a
    JOIN public.projects p ON p.id = a.project_id
    WHERE a.id = architecture_versions.architecture_id
    AND p.user_id = auth.uid()
  )
);

CREATE POLICY "Users can delete versions of their architectures"
ON public.architecture_versions FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM public.architectures a
    JOIN public.projects p ON p.id = a.project_id
    WHERE a.id = architecture_versions.architecture_id
    AND p.user_id = auth.uid()
  )
);

-- Function to auto-increment version number
CREATE OR REPLACE FUNCTION public.get_next_version_number(arch_id UUID)
RETURNS INTEGER AS $$
DECLARE
  next_version INTEGER;
BEGIN
  SELECT COALESCE(MAX(version_number), 0) + 1
  INTO next_version
  FROM public.architecture_versions
  WHERE architecture_id = arch_id;
  
  RETURN next_version;
END;
$$ LANGUAGE plpgsql;
